# Generated by Django 2.2.3 on 2019-07-17 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20190717_0756'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counrty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('population', models.FloatField(default=0)),
                ('acronym', models.CharField(max_length=4)),
            ],
        ),
    ]
