# Generated by Django 2.2.3 on 2019-07-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_counrty'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Counrty',
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(choices=[('Spain', 'ESP'), ('Mexico', 'MX'), ('Germany', 'GER'), ('France', 'FR'), ('Italy', 'IT')], max_length=50, null=True),
        ),
    ]
